[project]
name = "lpp-agent"
version = "0.2.0"
requires-python = ">=3.10.2
dependencies = [
  "requests>=2.31.0",
  # add your deps here
]

[project.scripts]
lpp-agent = "lpp_agent.main:cli"   # 👈 stable console entrypoint

[tool.setuptools.packages.find]
where = ["."]
include = ["lpp_agent*"]
